version: '3.7'

services:

  authentication:
    container_name: authentication-app
    image: gokulsarath05/authentication-app:1.0
    build: ./authentication/
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
    networks:
      - ecom-network
  
  product:
    container_name: product-app
    image: gokulsarath05/product-app:1.0
    build: ./product/
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    restart: always
    networks:
      - ecom-network

  catalog:
    container_name: catalog-app
    image: gokulsarath05/catalog-app:1.0
    build: ./catalog/
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - ecom-network

  order:
    container_name: order-app
    image: gokulsarath05/order-app:1.0
    build: ./order/
    ports:
      - "8083:8083"
    networks:
      - ecom-network

  mysql:
    container_name: mysql-database
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=ecommerce
    networks:
      - ecom-network

  mongodb:
    container_name: mongodb
    image: mongo:4.4.11
    restart: always
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge